### ISSUE TITLE
Directly accesing the Repository from controller, it should not

### ISSUE THREAD

**Issue by e-kola** [e-kola/Microservices-Quick-Start#5]
**Issue**:
Repository is a part of the service in N-tiered design, not a part of controller which should inject the service interface only.

**Sub-tasks**:
- [ ] Write an unit test for controllers to check that the injected interface is a service
- [ ] Write an unit test for services to check that the injected interface is a repository
- [ ] Re-factor DI in controllers and services
