### ISSUE TITLE
Unit tests do not use mocked dependencies

### ISSUE THREAD

**Issue by raman-m** [e-kola/Microservices-Quick-Start#6]
**Issue**:
Unit tests do not use mocked dependencies, so they are integration tests not unit tests. They should be separated.

**Sub-tasks**:
- [ ] Create IntegrationTests project for each related project
- [ ] Define base mocks for communication as base classes
- [ ] General integration tests for controllers
