### ISSUE TITLE
The posts vs the comments relationship

### ISSUE THREAD

**Issue by e-kola** [e-kola/Microservices-Quick-Start#7]
**Feature request**:
The old design/solution doesn't make any connection between the posts and the comments. New design should change communication of models to simple object referencing.

**Sub-tasks**:
- [ ] Ensure both Post and Comment models are placed into one microservice domain
- [ ] Define referencing of Comment to Post as many-to-one
- [ ] Change signatures of methods, update service implementations
- [ ] Unit tests for referencing relationship
